"""
Service Account Creation Task

Creates service accounts with server-generated (dynamic) credentials.
Credentials are written as JSON files to the output directory so that
other containers can consume them via a shared volume mount.

JSON config example:
{
  "service_accounts": [
    {
      "user": "app-service",
      "name": "My Service Account",
      "description": "Used by application X",
      "policy": "readwrite-documents"
    }
  ]
}

Output format (written to /data/credentials/<name>.json):
{
  "accessKey": "generated-access-key",
  "secretKey": "generated-secret-key",
  "user": "app-service",
  "name": "My Service Account"
}

Notes:
  - Credentials are dynamically generated by MinIO (not predetermined).
  - If a service account with the same name already exists for the user,
    it is skipped to preserve existing credentials.
  - The output directory defaults to /data/credentials/ and can be
    overridden via the MINIO_CREDENTIALS_DIR environment variable.
  - Other containers can mount the same volume to read credentials.
"""

import json
import os
import subprocess
import tempfile
from pathlib import Path

TASK_NAME = "Service Accounts"
TASK_DESCRIPTION = "Create service accounts with dynamic credentials"
CONFIG_KEY = "service_accounts"

MC_ALIAS = "minio"
CREDENTIALS_DIR = os.environ.get("MINIO_CREDENTIALS_DIR", "/data/credentials")


def _mc(args: list) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["mc", "--json"] + args,
        capture_output=True,
        text=True,
    )


def _find_existing_sa(user: str, sa_name: str) -> str | None:
    """Check if a service account with a given name exists for a user.

    Returns the access key if found, None otherwise.
    """
    result = _mc(["admin", "user", "svcacct", "list", MC_ALIAS, user])
    if result.returncode != 0:
        return None

    for line in result.stdout.strip().splitlines():
        try:
            data = json.loads(line)
            if data.get("name") == sa_name or data.get("description", "").startswith(sa_name):
                return data.get("accessKey")
        except json.JSONDecodeError:
            continue
    return None


def _write_credentials(sa_name: str, credentials: dict) -> str:
    """Write credentials to a JSON file in the output directory."""
    creds_dir = Path(CREDENTIALS_DIR)
    creds_dir.mkdir(parents=True, exist_ok=True)

    # Sanitize filename
    safe_name = sa_name.replace(" ", "-").replace("/", "-").lower()
    creds_file = creds_dir / f"{safe_name}.json"

    with open(creds_file, "w") as f:
        json.dump(credentials, f, indent=2)

    # Restrict permissions
    os.chmod(creds_file, 0o600)

    return str(creds_file)


def _create_sa(cmd: list, sa_policy: str | None) -> subprocess.CompletedProcess:
    """Create a service account, optionally with a scoped policy.

    Handles temp file creation and cleanup for the policy document.
    """
    policy_path = None

    try:
        if sa_policy and isinstance(sa_policy, str):
            # Fetch the named policy document from MinIO
            policy_result = _mc(["admin", "policy", "info", MC_ALIAS, sa_policy])
            if policy_result.returncode == 0:
                with tempfile.NamedTemporaryFile(
                    mode="w", suffix=".json", delete=False, prefix="sa-policy-"
                ) as f:
                    f.write(policy_result.stdout)
                    policy_path = f.name
                cmd.extend(["--policy", policy_path])

        return _mc(cmd)
    finally:
        if policy_path:
            os.unlink(policy_path)


def run(items: list, console, **kwargs) -> dict:
    if not items:
        return {"skipped": True, "message": "No service accounts configured"}

    created = 0
    skipped = 0

    for sa in items:
        parent_user = sa["user"]
        sa_name = sa.get("name", f"sa-{parent_user}")
        sa_description = sa.get("description", "")
        sa_policy = sa.get("policy")

        # Check if service account already exists for this user
        existing_key = _find_existing_sa(parent_user, sa_name)
        if existing_key:
            console.print(f"    [dim]Service account exists: {sa_name} ({existing_key})[/]")
            skipped += 1
            continue

        # Build command - let MinIO generate credentials
        cmd = ["admin", "user", "svcacct", "add", MC_ALIAS, parent_user]
        if sa_name:
            cmd.extend(["--name", sa_name])
        if sa_description:
            cmd.extend(["--description", sa_description])

        # Create the service account (with temp file cleanup for policy)
        result = _create_sa(cmd, sa_policy)

        if result.returncode == 0:
            created += 1

            # Parse the generated credentials from mc output
            credentials = {"user": parent_user, "name": sa_name}
            for line in result.stdout.strip().splitlines():
                try:
                    data = json.loads(line)
                    if "accessKey" in data:
                        credentials["accessKey"] = data["accessKey"]
                        credentials["secretKey"] = data.get("secretKey", "")
                        break
                except json.JSONDecodeError:
                    continue

            if credentials.get("accessKey"):
                creds_file = _write_credentials(sa_name, credentials)
                console.print(
                    f"    [green]Created service account: {sa_name} "
                    f"(parent: {parent_user})[/]"
                )
                console.print(f"    [dim]  Credentials written to: {creds_file}[/]")
            else:
                console.print(
                    f"    [green]Created service account: {sa_name} "
                    f"(parent: {parent_user})[/]"
                )
                console.print(f"    [yellow]  Warning: Could not parse generated credentials[/]")
        else:
            console.print(f"    [red]Failed to create SA {sa_name}: {result.stderr.strip()}[/]")

    total = len(items)
    return {
        "changed": created > 0,
        "message": f"{total} service account(s) processed ({created} created, {skipped} existing)",
    }
