"""
Service Account Creation Task

Creates service accounts with server-generated (dynamic) credentials.
Credentials are written as JSON files to the output directory so that
other containers can consume them via a shared volume mount.

JSON config example:
{
  "service_accounts": [
    {
      "user": "app-service",
      "name": "My Service Account",
      "description": "Used by application X",
      "policy": "readwrite-documents"
    }
  ]
}

Output format (written to /data/credentials/<name>.json):
{
  "accessKey": "generated-access-key",
  "secretKey": "generated-secret-key",
  "user": "app-service",
  "name": "My Service Account"
}

Notes:
  - Credentials are dynamically generated by MinIO (not predetermined).
  - If a service account with the same name already exists for the user,
    it is skipped to preserve existing credentials.
  - The output directory defaults to /data/credentials/ and can be
    overridden via the MINIO_CREDENTIALS_DIR environment variable.
  - Other containers can mount the same volume to read credentials.
  - "policy" restricts the account to that named policy: its document is
    exported with `mc admin policy info --policy-file` and passed to
    `svcacct add --policy`. Without "policy" the account inherits the
    parent user's permissions.
  - A service account whose parent user was skipped (optional user with an
    empty secret) or resolves to an empty name is skipped as well. Any other
    error (unknown parent user, unreadable policy, credentials that cannot be
    parsed) is a failure and the init container exits 1.
"""

import json
import os
import subprocess
import tempfile
from pathlib import Path

from ._mc import MC_ALIAS, fail, skip
from ._mc import mc as _mc

TASK_NAME = "Service Accounts"
TASK_DESCRIPTION = "Create service accounts with dynamic credentials"
CONFIG_KEY = "service_accounts"

CREDENTIALS_DIR = os.environ.get("MINIO_CREDENTIALS_DIR", "/data/credentials")


def _find_existing_sa(user: str, sa_name: str) -> str | None:
    """Check if a service account with a given name exists for a user.

    Returns the access key if found, None otherwise.
    """
    result = _mc(["admin", "user", "svcacct", "list", MC_ALIAS, user])
    if result.returncode != 0:
        return None

    for line in result.stdout.strip().splitlines():
        try:
            data = json.loads(line)
            if data.get("name") == sa_name or data.get("description", "").startswith(sa_name):
                return data.get("accessKey")
        except json.JSONDecodeError:
            continue
    return None


def _write_credentials(sa_name: str, credentials: dict) -> str:
    """Write credentials to a JSON file in the output directory."""
    creds_dir = Path(CREDENTIALS_DIR)
    creds_dir.mkdir(parents=True, exist_ok=True)

    # Sanitize filename
    safe_name = sa_name.replace(" ", "-").replace("/", "-").lower()
    creds_file = creds_dir / f"{safe_name}.json"

    with open(creds_file, "w") as f:
        json.dump(credentials, f, indent=2)

    # Restrict permissions
    os.chmod(creds_file, 0o600)

    return str(creds_file)


def _create_sa(cmd: list, sa_policy: str | None) -> subprocess.CompletedProcess:
    """Create a service account, optionally restricted to a named policy.

    `mc admin policy info --policy-file` exports the raw IAM document, which
    `svcacct add --policy` expects. A policy that cannot be exported fails the
    account rather than creating it with the parent user's full permissions.
    """
    if not sa_policy:
        return _mc(cmd)
    if not isinstance(sa_policy, str):
        return subprocess.CompletedProcess(cmd, 1, stdout="", stderr="policy must be the name of a policy")

    fd, policy_path = tempfile.mkstemp(suffix=".json", prefix="sa-policy-")
    os.close(fd)
    try:
        exported = _mc(["admin", "policy", "info", MC_ALIAS, sa_policy, "--policy-file", policy_path])
        if exported.returncode != 0:
            exported.stderr = f"read policy {sa_policy}: {exported.stderr}"
            return exported
        if os.path.getsize(policy_path) == 0:
            return subprocess.CompletedProcess(
                cmd, 1, stdout="", stderr=f"read policy {sa_policy}: mc exported an empty document"
            )
        return _mc(cmd + ["--policy", policy_path])
    finally:
        os.unlink(policy_path)


def run(items: list, console, **kwargs) -> dict:
    if not items:
        return {"skipped": True, "message": "No service accounts configured"}

    skipped_users = kwargs.get("context", {}).get("skipped_users", set())

    created = 0
    existing = 0
    skipped = 0
    failed = 0

    for sa in items:
        parent_user = sa["user"]
        sa_name = sa.get("name", f"sa-{parent_user}")
        sa_description = sa.get("description", "")
        sa_policy = sa.get("policy")

        if not parent_user or parent_user in skipped_users:
            skip(console, f"service account '{sa_name}': parent user '{parent_user}' was not created")
            skipped += 1
            continue

        # Check if service account already exists for this user
        existing_key = _find_existing_sa(parent_user, sa_name)
        if existing_key:
            console.print(f"    [dim]Service account exists: {sa_name} ({existing_key})[/]")
            existing += 1
            continue

        # Build command - let MinIO generate credentials
        cmd = ["admin", "user", "svcacct", "add", MC_ALIAS, parent_user]
        if sa_name:
            cmd.extend(["--name", sa_name])
        if sa_description:
            cmd.extend(["--description", sa_description])

        # Create the service account (with temp file cleanup for policy)
        result = _create_sa(cmd, sa_policy)

        if result.returncode != 0:
            fail(console, f"create service account {sa_name} (parent: {parent_user}): {result.stderr}")
            failed += 1
            continue

        created += 1

        # Parse the generated credentials from mc output
        credentials = {"user": parent_user, "name": sa_name}
        for line in result.stdout.strip().splitlines():
            try:
                data = json.loads(line)
                if "accessKey" in data:
                    credentials["accessKey"] = data["accessKey"]
                    credentials["secretKey"] = data.get("secretKey", "")
                    break
            except json.JSONDecodeError:
                continue

        console.print(
            f"    [green]Created service account: {sa_name} "
            f"(parent: {parent_user})[/]"
        )
        if credentials.get("accessKey"):
            creds_file = _write_credentials(sa_name, credentials)
            console.print(f"    [dim]  Credentials written to: {creds_file}[/]")
        else:
            # The account exists now, but nobody can use it: its secret is lost.
            fail(console, f"service account {sa_name}: could not parse the generated credentials")
            failed += 1

    total = len(items)
    msg = f"{total} service account(s) processed ({created} created, {existing} existing"
    if skipped:
        msg += f", {skipped} skipped"
    if failed:
        msg += f", {failed} failed"
    return {
        "changed": created > 0,
        "message": msg + ")",
        "failed": failed,
        "items_skipped": skipped,
    }
